[tool.poetry]
name = "Guitar Lesson Scheduler"
version = "0.1.0"
description = ""
authors = ["cap0n3 <cap0n3@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
